---
- name: Install desktop
  apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
  become: yes
  tags: sudo

- name: Install light
  apt:
      deb: https://github.com/haikarainen/light/releases/download/v1.2/light_1.2_amd64.deb
      state: present
  become: yes

- name: Install py3status
  shell: |
      pypi-install py3status --release 3.19
  args:
      creates: /usr/bin/py3status
  become: yes

- name: Create config directories
  file:
      path: ~/.config/{{ item }}
      state: directory
  loop:
      - fontconfig
      - gtk-3.0
      - i3
      - py3status
      - lxterminal
      - zathura

- name: Configure desktop
  template:
      src: "{{ item }}.j2"
      dest: ~/.{{ item }}
  loop:
      - config/fontconfig/fonts.conf
      - config/gtk-3.0/settings.ini
      - config/i3/config
      - config/py3status/config
      - config/lxterminal/lxterminal.conf
      - config/zathura/zathurarc
      - gtkrc-2.0
      - Xresources

- name: Download default desktop wallpaper
  get_url:
      url: https://raw.githubusercontent.com/unix121/i3wm-themer/master/src/wallpapers/000.png
      dest: /usr/share/backgrounds/unix121_wallpapers_000.png
  become: yes

- name: Configure LightDM
  template:
      src: lightdm-gtk-greeter.conf.j2
      dest: /etc/lightdm/lightdm-gtk-greeter.conf
      backup: yes
  become: yes
  tags: sudo
