---
- name: Install desktop
  apt:
      name: "{{ desktop_deb_packages }}"
      update_cache: yes
      state: latest
  become: yes
  tags: sudo

- name: Install py3status
  pip:
      name: py3status
      state: latest
      virtualenv: "{{ desktop_py3status_env }}"
      virtualenv_python: /usr/bin/python3

- name: Create config directories
  file:
      path: ~/.config/{{ item }}
      state: directory
  loop:
      - fontconfig
      - gtk-3.0
      - i3
      - py3status
      - lxterminal
      - zathura

- name: Configure desktop
  template:
      src: "{{ item }}.j2"
      dest: ~/.{{ item }}
  loop:
      - config/fontconfig/fonts.conf
      - config/gtk-3.0/settings.ini
      - config/i3/config
      - config/py3status/config
      - config/lxterminal/lxterminal.conf
      - config/zathura/zathurarc
      - gtkrc-2.0
      - Xresources

- name: Download default desktop wallpaper
  get_url:
      url: https://github.com/unix121/i3wm-themer/raw/master/wallpapers/000.png
      dest: /usr/share/backgrounds/unix121_wallpapers_000.png
  become: yes
  tags: sudo

- name: Configure LightDM
  template:
      src: lightdm-gtk-greeter.conf.j2
      dest: /etc/lightdm/lightdm-gtk-greeter.conf
      backup: yes
  become: yes
  tags: sudo

- name: Install deb packages (optional)
  apt:
      name: "{{ desktop_deb_packages_optional }}"
      update_cache: yes
      state: latest
  when: desktop_deb_packages_optional | length > 0
  become: yes
  tags: sudo

- name: Install snap packages (optional)
  snap:
      name: "{{ item.name }}"
      channel: "{{ item.channel | default('stable') }}"
      classic: "{{ item.classic | default('no') }}"
      state: present
  loop: "{{ desktop_snap_packages }}"
  when: desktop_snap_packages | length > 0
  become: yes
  tags: sudo
