---
- name: "tmux : Install tmux and git"
  apt:
      name: ["tmux", "git"]
      state: latest
      update_cache: yes
  become: yes
  tags: sudo

- name: "tmux : Create plugin directory"
  file:
      path: ~/.tmux/plugins
      state: directory

- name: "tmux : Install tpm"
  git:
      repo: https://github.com/tmux-plugins/tpm.git
      dest: ~/.tmux/plugins/tpm

- name: "tmux : Configure tmux"
  template:
      src: tmux.conf.j2
      dest: ~/.tmux.conf
