---
- name: Prepare the installation of i3-ubuntu
  hosts: localhost
  connection: local
  tasks:
      - name: Mount shared folder from host system
        mount:
            path: /mnt/shared
            src: Shared
            fstype: vboxsf
            opts: rw,uid={{ ansible_user_uid }},gid={{ ansible_user_gid }}
            state: mounted
            backup: yes
        become: yes
      - name: Link shared folder to home directory
        file:
            path: "{{ ansible_env['HOME'] }}/Shared"
            src: /mnt/shared
            state: link
      - name: Copy ssh key pair from host system
        copy:
            dest: "{{ ansible_env['HOME'] }}/.ssh/{{ item.name }}"
            src: /mnt/shared/keys/{{ item.name }}
            remote_src: yes
            mode: "{{ item.mode }}"
        loop:
            - { name: id_rsa, mode: 600 }
            - { name: id_rsa.pub, mode: 644 }
