---
- name: Install desktop
  apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
  become: yes

- name: Create config directories
  file:
      path: "{{ ansible_env['HOME'] }}/.config/{{ item }}"
      state: directory
  loop:
      - i3
      - i3status

- name: Configure desktop
  template:
      src: "{{ item.dirname }}/{{ item.filename }}.j2"
      dest: "{{ ansible_env['HOME'] }}/.config/{{ item.dirname }}/{{ item.filename }}"
  loop:
      - { dirname: "i3", filename: "config" }
      - { dirname: "i3status", filename: "config" }
