---
- name: Install desktop
  apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
  become: yes

- name: Create config directories
  file:
      path: ~/.config/{{ item }}
      state: directory
  loop:
      - fontconfig
      - gtk-3.0
      - i3
      - i3status
      - lxterminal
      - zathura

- name: Configure desktop
  template:
      src: "{{ item }}.j2"
      dest: ~/.{{ item }}
  loop:
      - config/fontconfig/fonts.conf
      - config/gtk-3.0/settings.ini
      - config/i3/config
      - config/i3status/config
      - config/lxterminal/lxterminal.conf
      - config/zathura/zathurarc
      - gtkrc-2.0
      - Xresources

- name: Configure LightDM
  template:
      src: lightdm-gtk-greeter.conf.j2
      dest: /etc/lightdm/lightdm-gtk-greeter.conf
      backup: yes
  become: yes
