---
- name: Install desktop
  apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
  become: yes

- name: Create config directories
  file:
      path: "{{ ansible_env['HOME'] }}/.config/{{ item }}"
      state: directory
  loop:
      - i3
      - i3status
      - lxterminal

- name: Configure desktop
  template:
      src: "{{ item.dir }}/{{ item.file }}.j2"
      dest: "{{ ansible_env['HOME'] }}/.config/{{ item.dir }}/{{ item.file }}"
  loop:
      - { dir: "i3", file: "config" }
      - { dir: "i3status", file: "config" }
      - { dir: "lxterminal", file: "lxterminal.conf" }
