---
- name: Install desktop
  apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
  become: yes

- name: Create config directories
  file:
      path: "{{ ansible_env['HOME'] }}/.config/{{ item }}"
      state: directory
  loop:
      - fontconfig
      - gtk-3.0
      - i3
      - i3status
      - lxterminal

- name: Configure desktop
  template:
      src: "{{ item }}.j2"
      dest: "{{ ansible_env['HOME'] }}/.{{ item }}"
  loop:
      - config/fontconfig/fonts.conf
      - config/gtk-3.0/settings.ini
      - config/i3/config
      - config/i3status/config
      - config/lxterminal/lxterminal.conf
      - gtkrc-2.0
      - Xresources
