---
- name: Install z-shell and git
  apt:
      name: ["zsh", "git"]
      state: latest
      update_cache: yes
  become: yes

- name: Change shell of user to z-shell
  user:
      name: "{{ ansible_user }}"
      shell: /bin/zsh
      state: present
  become: yes

- name: Install prezto
  git:
      repo: https://github.com/sorin-ionescu/prezto.git
      dest: ~/.zprezto

- name: Link prezto
  file:
      src: ~/.zprezto/runcoms/{{ item }}
      path: ~/.{{ item }}
      state: link
  loop:
      - zlogin
      - zlogout
      - zshenv

- name: Configure prezto
  copy:
      src: zpreztorc
      dest: ~/.zpreztorc

- name: Configure prezto
  template:
      src: "{{ item }}.j2"
      dest: ~/.{{ item }}
  loop:
      - zprofile
      - zshrc
