- name: "{{ nodeenv.name }} : Install nodeenv"
  pip:
      name: nodeenv
      state: latest
      virtualenv: ~/.virtualenvs/{{ nodeenv.name }}
      virtualenv_python: /usr/bin/python3

- name: "{{ nodeenv.name }} : Install Node.js {{ nodeenv.version }}"
  shell: |
      . ~/.virtualenvs/{{ nodeenv.name }}/bin/activate
      nodeenv -p -n {{ nodeenv.version }}
      deactivate
  args:
      creates: ~/.virtualenvs/{{ nodeenv.name }}/bin/node

- name: "{{ nodeenv.name }} : Add npm wrapper"
  template:
      src: npm.sh.j2
      dest: ~/.virtualenvs/{{ nodeenv.name }}/bin/npm.sh
      mode: 0775

- name: "{{ nodeenv.name }} : Install Node.js modules"
  npm:
      executable: ~/.virtualenvs/{{ nodeenv.name }}/bin/npm.sh
      name: "{{ item }}"
      global: yes
      state: latest
  loop: "{{ nodeenv.modules }}"
