---
- name: Create config directory
  file:
      path: ~/.ssh
      state: directory
      mode: 0700

- name: Configure ssh (optional)
  template:
      dest: ~/.ssh/config
      src: config.j2
  when: ssh_config is defined
