---
- name: Create config directory
  file:
      path: ~/.ssh
      state: directory
      mode: 0700

- name: Configure ssh (optional)
  template:
      dest: ~/.ssh/config
      src: config.j2
  when: ssh_config is defined

- name: "Ubuntu : Install mosh and sshfs"
  apt:
      name: ["mosh", "sshfs"]
      state: latest
      update_cache: yes
  when: ansible_distribution == "Ubuntu"
  become: yes
  tags: sudo
