---
- name: "ssh : Create config directory"
  file:
      path: ~/.ssh
      state: directory
      mode: 0700

- name: "ssh : Configure ssh (optional)"
  template:
      dest: ~/.ssh/config
      src: config.j2
      mode: 0644
  when: ssh_config is defined
