---
- name: Create config directory
  file:
      path: "{{ ansible_env['HOME'] }}/.ssh"
      state: directory
      mode: 0700

- name: Configure ssh (optional)
  copy:
      dest: "{{ ansible_env['HOME'] }}/.ssh/config"
      src: "{{ ssh_config_file }}"
  when: ssh_config_file is defined
