---
- name: Create config directory
  file:
      path: "{{ ansible_env['HOME'] }}/.ssh"
      state: directory

- name: Configure ssh
  copy:
      dest: "{{ ansible_env['HOME'] }}/.ssh/config"
      src: config
