---
- name: Create config directory
  file:
      path: ~/.ssh
      state: directory
      mode: 0700

- name: Configure ssh (optional)
  copy:
      dest: ~/.ssh/config
      src: "{{ ssh_config_file }}"
  when: ssh_config_file is defined

- name: Install mosh and sshfs
  apt:
      name: ["mosh", "sshfs"]
      state: latest
      update_cache: yes
  become: yes
