- name: Install system packages
  apt:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
  become: yes
  tags: sudo

- name: Install Python modules inside virtual environment
  pip:
      name: "{{ python_modules }}"
      state: latest
      virtualenv: ~/.virtualenvs/py2-std
      virtualenv_python: python2
      virtualenv_site_packages: yes

- name: Install IPython kernel
  shell: |
      . ~/.virtualenvs/py2-std/bin/activate
      python -m ipykernel install --user --name py2-std --display-name "Python 2 (py2-std)" 
      deactivate
  args:
      creates: ~/.local/share/jupyter/kernels/py2-std
