---
- name: "Ubuntu : Install git and git-lfs"
  apt:
      name: ["git", "git-lfs"]
      state: latest
      update_cache: yes
  when: ansible_distribution == "Ubuntu"
  become: yes
  tags: sudo

- name: "macOS : Install git and git-lfs"
  homebrew:
      name: ["git", "git-lfs"]
      state: latest
      update_homebrew: yes
  when: ansible_distribution == "MacOSX"

- name: Configure git (optional)
  git_config:
      name: "{{ item.key }}"
      value: "{{ item.value }}"
      scope: global
  loop: "{{ git_config }}"
