---
- name: Install pass
  apt:
      name: "pass"
      state: latest
      update_cache: yes
  become: yes

- name: Checkout passwords
  git:
      repo: "{{ passwords }}"
      dest: "{{ ansible_env['HOME'] }}/.password-store"
