---
- name: Install pass
  apt:
      name: pass
      state: latest
      update_cache: yes
  become: yes
  tags: sudo

- name: Checkout existing password store (optional)
  git:
      repo: "{{ password_store }}"
      dest: ~/.password-store
      accept_hostkey: yes
  when: password_store is defined

- name: Fix permissions of (empty) password store
  file:
      path: ~/.password-store
      state: directory
      mode: 0700

- name: Include browserpass tasks (optional)
  include_tasks: browserpass.yml
  when: install_browserpass
