---
- name: Install git, git-lfs, git-svn, svn, and gnupg
  apt:
      name: ["git", "git-lfs", "git-svn", "subversion", "gnupg"]
      state: latest
      update_cache: yes
  become: yes
  tags: sudo

- name: Configure git (optional)
  git_config:
      name: "{{ item.key }}"
      value: "{{ item.value }}"
      scope: global
  loop: "{{ git_config }}"

- name: Create config directory for svn
  file:
      path: ~/.subversion
      state: directory

- name: Configure svn
  copy:
      src: "{{ item }}"
      dest: ~/.subversion/{{ item }}
  loop:
      - config
      - servers
