---
- name: "pass : Ubuntu : Install pass"
  apt:
      name: pass
      state: latest
      update_cache: yes
  when: ansible_distribution == "Ubuntu"
  become: yes
  tags: sudo

- name: "pass : macOS : Install pass and pinentry-mac"
  homebrew:
      name: ["pass", "pinentry-mac"]
      state: latest
      update_homebrew: yes
  when: ansible_distribution == "MacOSX"

- name: "pass : macOS : Configure gpg to use pinentry-mac"
  copy:
      src: gpg-agent.conf
      dest: ~/.gnupg/gpg-agent.conf
  when: ansible_distribution == "MacOSX"

- name: "pass : Checkout existing password store (optional)"
  git:
      repo: "{{ pass_password_store }}"
      dest: ~/.password-store
      accept_hostkey: yes
  when: pass_password_store is defined

- name: "pass : Fix permissions of (empty) password store"
  file:
      path: ~/.password-store
      state: directory
      mode: 0700

- name: "pass : Ubuntu : Include browserpass tasks"
  include_tasks: browserpass/ubuntu.yml
  vars:
      pass_browserpass_dest: "{{ pass_browserpass.dest.ubuntu }}"
      pass_browserpass_prefix: "{{ pass_browserpass.prefix.ubuntu }}"
      pass_browserpass_url: "{{ pass_browserpass.url }}"
      pass_browserpass_version: "{{ pass_browserpass.version }}"
  when: ansible_distribution == "Ubuntu"
  tags: browserpass

- name: "pass : macOS : Include browserpass tasks"
  include_tasks: browserpass/macos.yml
  vars:
      pass_browserpass_dest: "{{ pass_browserpass.dest.macos }}"
      pass_borwserpass_prefix: "{{ pass_browserpass.prefix.macos }}"
  when: ansible_distribution == "MacOSX"
  tags: browserpass
