---
- name: "Ubuntu : Install pass"
  apt:
      name: pass
      state: latest
      update_cache: yes
  when: ansible_distribution == "Ubuntu"
  become: yes
  tags: sudo

- name: "macOS : Install pass"
  homebrew:
      name: pass
      state: latest
      update_homebrew: yes
  when: ansible_distribution == "MacOSX"

- name: Checkout existing password store (optional)
  git:
      repo: "{{ password_store }}"
      dest: ~/.password-store
      accept_hostkey: yes
  when: password_store is defined

- name: Fix permissions of (empty) password store
  file:
      path: ~/.password-store
      state: directory
      mode: 0700

- name: "Ubuntu : Include browserpass tasks"
  include_tasks: browserpass/ubuntu.yml
  vars:
      dest: "{{ browserpass.dest.ubuntu }}"
      prefix: "{{ browserpass.prefix.ubuntu }}"
      url: "{{ browserpass.url }}"
      version: "{{ browserpass.version }}"
  when: ansible_distribution == "Ubuntu"
  tags: browserpass

- name: "macOS : Include browserpass tasks"
  include_tasks: browserpass/macos.yml
  vars:
      dest: "{{ browserpass.dest.macos }}"
      prefix: "{{ browserpass.prefix.macos }}"
  when: ansible_distribution == "MacOSX"
  tags: browserpass
