---
- name: "node : Add nodejs key"
  apt_key:
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      state: present
  become: yes
  tags: sudo

- name: "node : Add nodejs repository"
  apt_repository:
      repo: deb https://deb.nodesource.com/node_{{ node_version }}.x/ {{ ansible_distribution_release }} main
      filename: nodesource
      state: present
  become: yes
  tags: sudo

- name: "node : Add nodejs source repository"
  apt_repository:
      repo: deb-src https://deb.nodesource.com/node_{{ node_version }}.x/ {{ ansible_distribution_release }} main
      filename: nodesource
      state: present
  become: yes
  tags: sudo

- name: "node : Install nodejs"
  apt:
      name: nodejs
      update_cache: yes
      state: latest
  become: yes
  tags: sudo
