---
- name: "users : Install sudo and zsh"
  apt:
      name: ["sudo", "zsh"]
      update_cache: yes
      state: latest
  become: yes
  tags: sudo

- name: "users : Include group tasks (optional)"
  include_tasks: groups.yml
  when: create_groups | length > 0

- name: "users : Include user tasks (optional)"
  include_tasks: users.yml
  when: create_users | length > 0
