---
- name: "neovim : Install Python2 client"
  pip:
      name: pynvim
      state: latest
      virtualenv: "{{ neovim_py2_env }}"
      virtualenv_python: "{{ neovim_py2_path }}"

- name: "neovim : Install Python3 client"
  pip:
      name: ["pynvim", "neovim-remote"]
      state: latest
      virtualenv: "{{ neovim_py3_env }}"
      virtualenv_python: "{{ neovim_py3_path }}"
