---
- name: "neovim : macOS : Install neovim and additional packages"
  homebrew:
      name: "{{ neovim_homebrew_packages }}"
      state: latest
      update_homebrew: yes

- name: "neovim : macOS: Install virtualenvwrapper"
  pip:
      name: virtualenvwrapper
      state: latest
      executable: /usr/local/bin/pip3

- name: "neovim : macOS : Include client tasks"
  include_tasks: client.yml
  vars:
      neovim_py3_path: "{{ neovim_py3_path_macos }}"
