---
- name: "Ubuntu : Include install tasks"
  include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: "macOS : Include install tasks"
  include_tasks: macos.yml
  when: ansible_distribution == "MacOSX"

- name: Create directory for nvr executable
  file:
      path: ~/.local/bin
      state: directory

- name: Link nvr executable
  file:
      path: ~/.local/bin/nvr
      src: "{{ py3_env }}/bin/nvr"
      state: link

- name: Create directory for runtime files
  file:
      path: ~/.local/share/nvim/site
      state: directory

- name: Install plugin manager
  git:
      repo: https://github.com/junegunn/vim-plug.git
      dest: ~/.local/share/nvim/site/autoload

- name: Create directory for plugins
  file:
      path: "{{ plugin_directory }}"
      state: directory

- name: Install plugins
  git:
      repo: https://github.com/{{ item }}.git
      dest: "{{ plugin_directory }}/{{ item.split('/')[1] }}"
  loop: "{{ plugins }}"

- name: Create config directory
  file:
      path: ~/.config/nvim
      state: directory

- name: Configure neovim
  template:
      src: init.vim.j2
      dest: ~/.config/nvim/init.vim
