---
- name: Add neovim repository
  apt_repository:
      repo: ppa:neovim-ppa/stable
      state: present
      update_cache: yes
  become: yes
  tags: sudo

- name: Install neovim and additional packages
  apt:
      name: "{{ packages }}"
      state: latest
  become: yes
  tags: sudo

- name: Install Python2 client
  pip:
      name: pynvim
      state: latest
      virtualenv: "{{ py2_env }}"
      virtualenv_python: /usr/bin/python2

- name: Install Python3 client
  pip:
      name: ["pynvim", "neovim-remote"]
      state: latest
      virtualenv: "{{ py3_env }}"
      virtualenv_python: /usr/bin/python3

- name: Create directory for nvr executable
  file:
      path: ~/.local/bin
      state: directory

- name: Link nvr executable
  file:
      path: ~/.local/bin/nvr
      src: "{{ py3_env }}/bin/nvr"
      state: link

- name: Create directory for runtime files
  file:
      path: ~/.local/share/nvim/site
      state: directory

- name: Install plugin manager
  git:
      repo: https://github.com/junegunn/vim-plug.git
      dest: ~/.local/share/nvim/site/autoload

- name: Create directory for plugins
  file:
      path: "{{ plugin_directory }}"
      state: directory

- name: Install plugins
  git:
      repo: https://github.com/{{ item }}.git
      dest: "{{ plugin_directory }}/{{ item.split('/')[1] }}"
  loop: "{{ plugins }}"

- name: Create config directory
  file:
      path: ~/.config/nvim
      state: directory

- name: Configure neovim
  template:
      src: init.vim.j2
      dest: ~/.config/nvim/init.vim
