---
- name: "neovim : Ubuntu : Include install tasks"
  include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: "neovim : macOS : Include install tasks"
  include_tasks: macos.yml
  when: ansible_distribution == "MacOSX"

- name: "neovim : Create directory for nvr executable"
  file:
      path: ~/.local/bin
      state: directory

- name: "neovim : Link nvr executable"
  file:
      path: ~/.local/bin/nvr
      src: "{{ neovim_py3_env }}/bin/nvr"
      state: link

- name: "neovim : Create directory for runtime files"
  file:
      path: ~/.local/share/nvim/site
      state: directory

- name: "neovim : Install plugin manager"
  git:
      repo: https://github.com/junegunn/vim-plug.git
      dest: ~/.local/share/nvim/site/autoload

- name: "neovim : Create directory for plugins"
  file:
      path: "{{ neovim_plugin_directory }}"
      state: directory

- name: "neovim : Install plugins"
  git:
      repo: https://github.com/{{ item }}.git
      dest: "{{ neovim_plugin_directory }}/{{ item.split('/')[1] }}"
  loop: "{{ neovim_plugins }}"

- name: "neovim : Install vimtex plugin"
  git:
      repo: https://github.com/lervag/vimtex.git
      dest: "{{ neovim_plugin_directory }}/vimtex"
  when: neovim_vimtex_support

- name: "neovim : Create config directory"
  file:
      path: ~/.config/nvim
      state: directory

- name: "neovim : Install coc.nvim plugin"
  git:
      repo: https://github.com/neoclide/coc.nvim.git
      dest: "{{ neovim_plugin_directory }}/coc.nvim"
      version: release
  when: neovim_coc_support

- name: "neovim : Copy config for coc.nvim into config directory"
  copy:
      src: coc.vim
      dest: ~/.config/nvim/coc.vim
  when: neovim_coc_support

- name: "neovim : Copy settings for coc.nvim into config directory"
  copy:
      src: coc.json
      dest: ~/.config/nvim/coc-settings.json
  when: neovim_coc_support

- name: "neovim : Configure neovim"
  template:
      src: init.vim.j2
      dest: ~/.config/nvim/init.vim
