---
- name: "neovim : Ubuntu : Add neovim repository"
  apt_repository:
      repo: ppa:neovim-ppa/stable
      state: present
      update_cache: yes
  become: yes
  tags: sudo
  when: ansible_distribution_version == "18.04"

- name: "neovim : Ubuntu : Install neovim and additional packages"
  apt:
      name: "{{ neovim_deb_packages }}"
      state: latest
  become: yes
  tags: sudo

- name: "neovim : Ubuntu : Include client tasks"
  include_tasks: client.yml
  vars:
      neovim_py3_path: "{{ neovim_py3_path_ubuntu }}"
