---
- name: "prezto : Ubuntu : Include z-shell tasks"
  include_tasks: zsh/ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: "prezto : macOS : Include z-shell tasks"
  include_tasks: zsh/macos.yml
  when: ansible_distribution == "MacOSX"

- name: "prezto : Install prezto"
  git:
      repo: https://github.com/sorin-ionescu/prezto.git
      dest: ~/.zprezto

- name: "prezto : Link prezto"
  file:
      src: ~/.zprezto/runcoms/{{ item }}
      path: ~/.{{ item }}
      state: link
  loop:
      - zlogin
      - zlogout
      - zshenv

- name: "prezto : Configure prezto"
  template:
      src: "{{ item }}.j2"
      dest: ~/.{{ item }}
  loop:
      - zpreztorc
      - zprofile
      - zshrc
