---
- name: "prezto : Ubuntu : Install z-shell and git"
  apt:
      name: ["zsh", "git"]
      state: latest
      update_cache: yes
  become: yes
  tags: sudo

- name: "prezto : Ubuntu : Install keychain and socat"
  apt:
      name: ["keychain", "socat"]
      state: latest
      update_cache: yes
  when: prezto_keychain
  become: yes
  tags: sudo

- name: "prezto : Ubuntu : Change user's shell to z-shell"
  user:
      name: "{{ ansible_user_id }}"
      shell: /bin/zsh
      state: present
  become: yes
  tags: sudo
