---
- name: "python : macOS : Install homebrew packages"
  homebrew:
      name: "{{ python_homebrew_packages }}"
      state: latest
      update_homebrew: yes

- name: "python : macOS : Install Python packages"
  pip:
      name: "{{ python_packages_macos }}"
      state: latest
      executable: /usr/local/bin/pip3

- name: "python : macOS : Install virtual Python environments"
  include_tasks: pyenv.yml
  loop: "{{ python_envs }}"
  loop_control:
      loop_var: python_env
  vars:
      python_path_jupyter_kernels: "{{ python_path_jupyter_kernels_macos }}"
