- name: "{{ python_env.name }} : Install Python modules"
  pip:
      name: "{{ python_env.modules }}"
      state: latest
      virtualenv: ~/.virtualenvs/{{ python_env.name }}
      virtualenv_python: "{{ python_env.version }}"
      virtualenv_site_packages: "{{ python_env.site_packages | default('no') }}"

- name: "{{ python_env.name }} : Install IPython kernel (optional)"
  shell: |
      . ~/.virtualenvs/{{ python_env.name }}/bin/activate
      python -m ipykernel install --user \
          --name "{{ python_env.name }}" \
          --display-name "{{ python_env.longname }}"
      deactivate
  args:
      creates: "{{ python_path_jupyter_kernels }}/{{ python_env.name }}"
  when: "'kernel' in python_env and python_env.kernel"
