---
- name: Install light
  apt:
      deb: https://github.com/haikarainen/light/releases/download/v1.2/light_1.2_amd64.deb
      state: present
  become: yes
  tags: sudo

- name: Add user to video group
  user:
      name: "{{ ansible_user }}"
      groups: ["video"]
      append: yes
  become: yes
  tags: sudo

- name: Add udev rules
  template:
      src: backlight.rules.j2
      dest: /etc/udev/rules.d/backlight.rules
      owner: root
      group: root
  become: yes
  tags: sudo
