---
- name: Add neovim repository
  apt_repository:
      repo: ppa:neovim-ppa/stable
      state: present
      update_cache: yes
  become: yes

- name: Install neovim, powerline fonts, git, and virtualenvwrapper
  apt:
      name: ["neovim", "fonts-powerline", "git", "virtualenvwrapper"]
      state: latest
  become: yes

- name: Install Python2 client
  pip:
      name: neovim
      state: latest
      virtualenv: "{{ py2_env }}"
      virtualenv_python: python2

- name: Install Python3 client
  pip:
      name: ["neovim", "neovim-remote"]
      state: latest
      virtualenv: "{{ py3_env }}"
      virtualenv_python: python3

- name: Create directory for runtime files
  file:
      path: ~/.local/share/nvim/site
      state: directory

- name: Install plugin manager
  git:
      repo: https://github.com/junegunn/vim-plug.git
      dest: ~/.local/share/nvim/site/autoload

- name: Create directory for plugins
  file:
      path: "{{ plugin_directory }}"
      state: directory

- name: Install plugins
  git:
      repo: https://github.com/{{ item }}.git
      dest: "{{ plugin_directory }}/{{ item.split('/')[1] }}"
  loop: "{{ plugins }}"

- name: Create config directory
  file:
      path: ~/.config/nvim
      state: directory

- name: Configure neovim
  template:
      src: init.vim.j2
      dest: ~/.config/nvim/init.vim
