---
- name: Add neovim repository
  apt_repository:
      repo: ppa:neovim-ppa/stable
      state: present
      update_cache: yes
  become: yes

- name: Install neovim
  apt:
      name: ["neovim", "fonts-powerline", "git", "virtualenvwrapper"]
      state: latest
  become: yes

- name: Install Python2 client
  pip:
      name: neovim
      state: latest
      virtualenv: "{{ py2env }}"
      virtualenv_python: python2

- name: Install Python3 client
  pip:
      name: neovim
      state: latest
      virtualenv: "{{ py3env }}"
      virtualenv_python: python3

- name: Create directory for neovim runtime files
  file:
      path: "{{ ansible_env['HOME'] }}/.local/share/nvim/site"
      state: directory

- name: Install plugin manager
  git:
      repo: https://github.com/junegunn/vim-plug.git
      dest: "{{ ansible_env['HOME'] }}/.local/share/nvim/site/autoload"

- name: Create config directory
  file:
      path: "{{ ansible_env['HOME'] }}/.config/nvim"
      state: directory

- name: Configure neovim
  template:
      src: init.vim.j2
      dest: "{{ ansible_env['HOME'] }}/.config/nvim/init.vim"
