---
- name: Add neovim repository
  apt_repository:
      repo: ppa:neovim-ppa/stable
      state: present
      update_cache: yes
  become: yes

- name: Install neovim with clipboard support
  apt:
      name: ["neovim", "xclip"]
      state: latest
  become: yes

- name: Support virtual Python environments
  apt:
      name: virtualenvwrapper
      state: latest
  become: yes

- name: Install Python2 client
  pip:
      name: neovim
      virtualenv: "{{ ansible_env['HOME'] }}/.virtualenvs/py2-neovim"
      virtualenv_python: python2
      state: latest

- name: Install Python3 client
  pip:
      name: neovim
      virtualenv: "{{ ansible_env['HOME'] }}/.virtualenvs/py3-neovim"
      virtualenv_python: python3
      state: latest
