---
- name: "browserpass : macOS : Add homebrew tap"
  homebrew_tap:
      name: amar1729/formulae
      state: present

- name: "browserpass : macOS : Install"
  homebrew:
      name: browserpass
      state: latest
      update_homebrew: yes

- name: "pass : browserpass : macOS : Include config tasks"
  include_tasks: config.yml
  vars:
      os: macOS
