---
- name: "pass : browserpass : Ubuntu : Create install directory"
  file:
      path: "{{ pass_browserpass_prefix }}"
      state: directory

- name: "pass : browserpass : Ubuntu: Download browserpass"
  unarchive:
      src: "{{ pass_browserpass_url }}/{{ pass_browserpass_version }}/browserpass-linux64-{{ pass_browserpass_version }}.tar.gz"
      remote_src: yes
      dest: "{{ pass_browserpass_prefix }}"
      creates: "{{ pass_browserpass_prefix }}/browserpass-linux64-{{ pass_browserpass_version }}"

- name: "pass : browserpass : Ubuntu : Check for existing installation"
  stat:
      path: "{{ pass_browserpass_prefix }}/bin/browserpass-linux64"
  register: binary

- name: "pass : browserpass : Ubuntu : Configure installation"
  make:
      chdir: "{{ pass_browserpass_prefix }}/browserpass-linux64-{{ pass_browserpass_version }}"
      target: configure
      params:
          PREFIX: "{{ pass_browserpass_prefix | expanduser }}"
          BIN: browserpass-linux64
  when: not binary.stat.exists

- name: "pass : browserpass : Ubuntu : Install browserpass"
  make:
      chdir: "{{ pass_browserpass_prefix }}/browserpass-linux64-{{ pass_browserpass_version }}"
      target: install
      params:
          PREFIX: "{{ pass_browserpass_prefix | expanduser }}"
          BIN: browserpass-linux64
  when: not binary.stat.exists

- name: "pass : browserpass : Ubuntu : Include config tasks"
  include_tasks: config.yml
